"""Datasets for the omics-augmentation experiment.

Two sources:

* **Real**: MetaboLights MTBLS1 (a small, public, tabular metabolomics study). Download it
  manually - see the module README - and point ``--data`` at the CSV. It is intentionally not
  downloaded automatically: the point of the module is the experiment, not the plumbing.
* **Demo**: a synthetic two-batch cohort generated by :func:`synthetic_cohort`, with the same
  shape as the real thing (two classes, a few dozen features, an internal and an external batch).
  The external batch carries a batch offset, which is what makes the question interesting.
"""

from __future__ import annotations

import numpy as np
import pandas as pd


def synthetic_cohort(n_internal: int = 200, n_external: int = 120, n_features: int = 60,
                     n_informative: int = 8, batch_shift: float = 0.9,
                     seed: int = 0) -> pd.DataFrame:
    """Two batches, two classes, and a batch effect that is correlated with the class labels.

    The last part is deliberate. A batch effect that is independent of the label is harmless for
    an internal split and mostly harmless externally; a batch effect that is *entangled* with the
    label is what makes synthetic patients dangerous.
    """
    rng = np.random.default_rng(seed)

    def block(n: int, prevalence: float, shift: float) -> tuple[np.ndarray, np.ndarray]:
        y = (rng.random(n) < prevalence).astype(int)
        x = rng.standard_normal((n, n_features))
        # informative features: class-dependent signal
        x[:, :n_informative] += 1.1 * y[:, None]
        # batch offset, partly aligned with the label (the entanglement)
        offset = shift * rng.standard_normal(n_features)
        offset[:n_informative] += 0.35 * shift
        x += offset[None, :]
        # a few features are shifted differently in the two classes (a batch x label interaction)
        x[:, 2:5] += 0.5 * shift * y[:, None]
        return x, y

    x_in, y_in = block(n_internal, prevalence=0.5, shift=0.0)
    x_ex, y_ex = block(n_external, prevalence=0.4, shift=batch_shift)

    frame = pd.DataFrame(
        np.vstack([x_in, x_ex]),
        columns=[f"f{i:02d}" for i in range(n_features)],
    )
    frame["label"] = np.r_[y_in, y_ex]
    frame["batch"] = ["internal"] * n_internal + ["external"] * n_external
    return frame


def load_mtbls1(path: str) -> pd.DataFrame:
    """Load a prepared MTBLS1 table (samples x metabolites + ``label`` [+ ``batch``]).

    Expected format: one row per sample, a ``label`` column (0/1), optionally a ``batch`` column.
    The module README documents how to obtain and reshape the public study.
    """
    frame = pd.read_csv(path)
    if "label" not in frame.columns:
        raise ValueError("expected a 'label' column with 0/1 values")
    frame["label"] = frame["label"].astype(int)
    if "batch" not in frame.columns:
        frame["batch"] = "single"
    return frame


def split(frame: pd.DataFrame, test_size: float = 0.3, seed: int = 0):
    """Internal train / internal test / external split."""
    rng = np.random.default_rng(seed)
    internal = frame[frame["batch"] == "internal"]
    external = frame[frame["batch"] != "internal"]
    idx = rng.permutation(len(internal))
    n_test = int(len(internal) * test_size)
    test_idx, train_idx = idx[:n_test], idx[n_test:]
    feature_cols = [c for c in frame.columns if c not in ("label", "batch")]
    return (
        internal.iloc[train_idx], internal.iloc[test_idx], external, feature_cols,
    )
